project:
  type: website
  output-dir: docs

website:
  title: "Dr. İsmail Bekar"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: Media

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: article

editor: visual

